#ifndef ETSI_ITS_PARSER_MESSAGE_ID_H
#define ETSI_ITS_PARSER_MESSAGE_ID_H

enum {
    MESSAGE_ID_DENM = 1,
    MESSAGE_ID_CAM,
    MESSAGE_ID_POIM,
    MESSAGE_ID_SPATEM,
    MESSAGE_ID_MAPEM,
    MESSAGE_ID_IVIM,
    MESSAGE_ID_RFU1,
    MESSAGE_ID_RFU2,
    MESSAGE_ID_SREM,
    MESSAGE_ID_SSEM,
    MESSAGE_ID_EVCSN,
    MESSAGE_ID_SAEM,
    MESSAGE_ID_RTCMEM,
    MESSAGE_ID_CPM,
    MESSAGE_ID_IMZM,
    MESSAGE_ID_VAM,
    MESSAGE_ID_DSM,
    MESSAGE_ID_PCIM,
    MESSAGE_ID_PCVM,
    MESSAGE_ID_MCM,
    MESSAGE_ID_PAM,
};

#endif //ETSI_ITS_PARSER_MESSAGE_ID_H
